ControllRR.Presentation/Controllers/SectorsController.cs
using System.Diagnostics;
using ControllRR.Application.Dto;
using ControllRR.Application.Interfaces;
using ControllRR.Presentation.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ControllRR.Presentation.Controllers;

public class SectorsController : Controller
{
    private readonly ISectorService _sectorService;
    public SectorsController(ISectorService sectorService)
    {
        _sectorService = sectorService;
    }


    [Authorize(Roles = "Manager, Admin")]
    [HttpGet]
    public async Task<IActionResult> CreateNewSector()
    {
        return View();
    }

    [Authorize(Roles = "Manager, Admin")]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> CreateNewSector(SectorDto sectorDto)
    {
        if (!ModelState.IsValid)
        {
            TempData["SuccessMessage"] = "Setor Não pode ser inserido!";
            return View(sectorDto);
        }
        await _sectorService.InsertAsync(sectorDto);
        return RedirectToAction("GetAll");

    }

    [Authorize(Roles = "Manager, Admin")]
    [HttpGet]
    public async Task<IActionResult> GetAll()
    {
        return View();
    }

    [Authorize(Roles = "Manager, Admin")]
    [HttpPost]
    public async Task<IActionResult> GetList()
    {
        var draw = Request.Form["draw"].FirstOrDefault();
        var start = Convert.ToInt32(Request.Form["start"].FirstOrDefault() ?? "0");
        var length = Convert.ToInt32(Request.Form["length"].FirstOrDefault() ?? "10");
        var searchValue = Request.Form["search[value]"].FirstOrDefault()?.ToLower();
        var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"] + "][data]"].FirstOrDefault();
        var sortDirection = Request.Form["order[0][dir]"].FirstOrDefault();

        var result = await _sectorService.GetSectorAsync(
            start, length, searchValue, sortColumn, sortDirection);

        return Json(result);
    }
    //
    
    [Authorize(Roles = "Manager, Admin")]
    public async Task<IActionResult> SectorDetails(int id)
    {
        if (id == null)
        {
            return RedirectToAction(nameof(Error), new { message = "Não foi fornecido um id valido!" });
        }

        var sector = await _sectorService.FindByIdAsync(id);
        if (sector == null)
        {
            return RedirectToAction(nameof(Error), new { messgae = "O setor informado não foi encontrado." });
        }
        return View(sector);

    }

    [Authorize(Roles = "Admin")]
    [HttpGet]
    public async Task<IActionResult> SectorEdit(int id)
    {
        var sector = await _sectorService.FindByIdAsync(id);
        return View(sector);
    }

    [Authorize(Roles = "Admin")]
    [HttpPost]
    public async Task<IActionResult> SectorEdit(int? id, SectorDto sectorDto)
    {
        if (!ModelState.IsValid)
        {
            TempData["ErrorMessage"] = "Setor não pode ser alterado";
            var sectorView = await _sectorService.FindByIdAsync(id.Value);
            return View(sectorView);
        }
        try
        {
            await _sectorService.UpdateAsync(sectorDto);
            TempData["SuccessMessage"] = "Setor alterado com sucesso.";
            return RedirectToAction(nameof(GetAll));

        }
        catch (ApplicationException e)
        {
            return RedirectToAction(nameof(Error), new { message = e.Message });
        }



    }

    [Authorize(Roles = "Manager, Admin")]
    public async Task<IActionResult> Error(string message)
    {
        var viewModel = new ErrorViewModel
        {
            Message = message,
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
        };
        return View(viewModel);
    }

}

ControllRR.Presentation/Views/Sectors/Partials/_EditSectorForm.cshtml
@model ControllRR.Application.Dto.SectorDto;

<form asp-controller="Sectors" asp-action="SectorEdit" method="post">
    <div class="row">
     <div class="form-group col-md-2">
    <label asp-for="Name"></label>
    <input asp-for="Name" class="form-control input-sm" />
    <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group col-md-3">
    <label asp-for="Location"></label>
    <input asp-for="Location" class="form-control input-sm" />
    <span asp-validation-for="Location" class="text-danger"></span>
    </div> 
    <div class="form-group col-md-4">
    <label asp-for="Address"></label>
    <input asp-for="Address" class="form-control input-sm" />
    <span asp-validation-for="Address" class="text-danger"></span>
    </div> 
    <div class="col">
    <label asp-for="Number"></label>
    <input asp-for="Number" class="form-control input-sm" />
    <span asp-validation-for="Number" class="text-danger"></span>
    </div> 
    <div class="form-group col-md-2">
    <label asp-for="Neighborhood"></label>
    <input asp-for="Neighborhood" class="form-control input-sm" />
    <span asp-validation-for="Neighborhood" class="text-danger"></span>
    </div> 
    <div class="form-group col-md-3">
    <label asp-for="City"></label>
    <input asp-for="City" class="form-control input-sm" />
    <span asp-validation-for="City" class="text-danger"></span>
    </div> 
    <div class="form-group col-md-2">
    <label asp-for="Cep"></label>
    <input asp-for="Cep" class="form-control input-sm" />
    <span asp-validation-for="Cep" class="text-danger"></span>
    </div> 
    <div class="col">
    <label asp-for="RequesterName"></label>
    <input asp-for="RequesterName" class="form-control input-sm" />
    <span asp-validation-for="RequesterName" class="text-danger"></span>
    </div> 
    </div>
    <div class="mt-4">
    <button type="submit" class="btn btn-success">Salvar</button>
    </div>
</form>

ControllRR.Presentation/Views/Sectors/Partials/_GetAllSectors.cshtml
@model ControllRR.Application.Dto.SectorDto;
@{
   
    ViewData["Title"]="Consulta de Setores";
}
@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @TempData["SuccessMessage"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        @TempData["ErrorMessage"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
<div class="container-fluid px-4">
    <h1 class="mt-4"></h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="/Sectors/GetAll">Setores</a></li>
          <li class="breadcrumb-item active">Filtrar</li>
    </ol>
</div>

<div class="container">
    <div class="card">
        <div class="card-header">
            Data:: -- Setores Disponiveis ::
        </div>
   
<div class="row">
<div class="col-md-12">

<div class="container">
    <div class="table-responsive">
        <table id="deviceTable" class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Sub Setor</th>
                    <th>Local</th>
                    <th>Responsavel</th>
                      <th>Endereço</th>
                    <th>Ações Disponiveis</th>
                </tr>
            </thead>
            <tbody>
               
            </tbody>
             
        </table>
    </div>
</div>
</div>
</div>

ControllRR.Presentation/Views/Sectors/Partials/_NewSectorForm.cshtml
@model ControllRR.Application.Dto.SectorDto;

<form asp-controller="Sectors" asp-action="CreateNewSector" method="post">
    <div class="row">
     <div class="form-group col-md-2">
    <label asp-for="Name"></label>
    <input asp-for="Name" class="form-control input-sm" />
    <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group col-md-3">
    <label asp-for="Location"></label>
    <input asp-for="Location" class="form-control input-sm" />
    <span asp-validation-for="Location" class="text-danger"></span>
    </div> 
    <div class="form-group col-md-4">
    <label asp-for="Address"></label>
    <input asp-for="Address" class="form-control input-sm" />
    <span asp-validation-for="Address" class="text-danger"></span>
    </div> 
    <div class="col">
    <label asp-for="Number"></label>
    <input asp-for="Number" class="form-control input-sm" />
    <span asp-validation-for="Number" class="text-danger"></span>
    </div> 
    <div class="form-group col-md-2">
    <label asp-for="Neighborhood"></label>
    <input asp-for="Neighborhood" class="form-control input-sm" />
    <span asp-validation-for="Neighborhood" class="text-danger"></span>
    </div> 
    <div class="form-group col-md-3">
    <label asp-for="City"></label>
    <input asp-for="City" class="form-control input-sm" />
    <span asp-validation-for="City" class="text-danger"></span>
    </div> 
    <div class="form-group col-md-2">
    <label asp-for="Cep"></label>
    <input asp-for="Cep" class="form-control input-sm" />
    <span asp-validation-for="Cep" class="text-danger"></span>
    </div> 
    <div class="col">
    <label asp-for="RequesterName"></label>
    <input asp-for="RequesterName" class="form-control input-sm" />
    <span asp-validation-for="RequesterName" class="text-danger"></span>
    </div> 
    </div>
    <div class="mt-4">
    <button type="submit" class="btn btn-success">Salvar</button>
    </div>
</form>